language: node_js

node_js:
  - v7

env:
  global:
  matrix:
    - TRAVIS_MATRIX=test
    - TRAVIS_MATRIX=build

script:
  npm run $TRAVIS_MATRIX

after_success:
  - node scripts/deploy

branches:
  except:
    - /^v?\d+\.\d+\.\d+/
